server = "54.153.118.87"
port = 8889

profile_path = "data/reference-data/darknet.profile.csv"
source_path = "data/reference-data/darknet.source.csv"
stat_path = "data/reference-data/darknet.stat.csv"
