[package]
name = "evaluation"
version = "0.1.0"
authors = ["Ben Zhang <benzh@cs.berkeley.edu>"]

[dependencies]
csv = "0.15.0"
itertools = "0.5.9"
log = "*"
rand = "*"
rayon = "0.6.0"
rustc-serialize = "0.3"
structopt = "0.1.0"
structopt-derive = "0.1.0"
