[package]
name = "evaluation"
version = "0.1.0"
authors = ["Ben Zhang <benzh@cs.berkeley.edu>"]

[dependencies]
csv = "1.0.0-beta.4"
itertools = "0.5.9"
log = "*"
rand = "*"
rayon = "0.6.0"
structopt = "0.1.0"
structopt-derive = "0.1.0"
serde = "1.0"
serde_derive = "1.0"