#!/bin/bash
# -*- mode: sh -*-

declare -i client_pid
declare -i timer_pid

function main() {
    sudo LATENCY="200ms 20ms" ./shaper start eth0 100000kbit

    trap "stop" SIGHUP SIGINT SIGTERM
    ##
    ## Client
    ##
    pushd . > /dev/null
    cd  ../runtime
    RUST_LOG=awstream=info cargo run --release --bin client 2> stderr.log &
    client_pid=$!
    popd > /dev/null

    ##
    ## Start timeout
    ##
    timeout_seconds=260
    sleep $timeout_seconds && stop &
    timer_pid=$!

    ##
    ## Traffic shaping
    ##
    sudo ./scheduled_shape eth0 \
         100000kbit 40 \
         7500kbit 180 \
         100000kbit 40
}

function stop() {
    echo "stop all"
    echo "killing client with pid" $client_pid
    echo "killing timer with pid" $timer_pid
    sudo kill -TERM $client_pid &>/dev/null
    sudo kill -TERM $timer_pid &>/dev/null
}

main
